In [6]:
import numpy as np


def checkers_grid(shape, sq_size, odd_even=1):
    if odd_even not in (0, 1):
        raise ValueError('odd_even must be 0 or 1')
    grid = np.zeros(shape, dtype=int)
    ind = np.indices(grid.shape)
    grid[(ind[0] // sq_size + ind[1] // sq_size) % 2 == odd_even] = 1
    return grid

print(checkers_grid((24, 32), 4, 0))

[[1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0]
 [1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0]
 [1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0]
 [1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]
 [0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]
 [0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]
 [0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0]
 [1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0]
 [1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0]
 [1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]
 [0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]
 [0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 

In [37]:
def create_circular_array(size, max_value):
    center = (size - 1) / 2
    array = np.zeros((size, size))
    for i in range(size):
        for j in range(size):
            distance = np.sqrt((i - center) ** 2 + (j - center) ** 2)
            array[i, j] = max(0, max_value - distance)
    return array

circular_array = create_circular_array(9, 9)
print(circular_array)

[[3.34314575 4.         4.52786405 4.87689437 5.         4.87689437
  4.52786405 4.         3.34314575]
 [4.         4.75735931 5.39444872 5.83772234 6.         5.83772234
  5.39444872 4.75735931 4.        ]
 [4.52786405 5.39444872 6.17157288 6.76393202 7.         6.76393202
  6.17157288 5.39444872 4.52786405]
 [4.87689437 5.83772234 6.76393202 7.58578644 8.         7.58578644
  6.76393202 5.83772234 4.87689437]
 [5.         6.         7.         8.         9.         8.
  7.         6.         5.        ]
 [4.87689437 5.83772234 6.76393202 7.58578644 8.         7.58578644
  6.76393202 5.83772234 4.87689437]
 [4.52786405 5.39444872 6.17157288 6.76393202 7.         6.76393202
  6.17157288 5.39444872 4.52786405]
 [4.         4.75735931 5.39444872 5.83772234 6.         5.83772234
  5.39444872 4.75735931 4.        ]
 [3.34314575 4.         4.52786405 4.87689437 5.         4.87689437
  4.52786405 4.         3.34314575]]


In [22]:
from scipy.optimize import curve_fit
import numpy as np

# Create a 2D array with a Gaussian function
def create_gaussian_array(shape, middle, amp, k, sigma):
    a, b = middle
    x, y = np.indices(shape)
    array = np.zeros(shape)
    array = amp * np.exp(-((x - a) ** 2 + (y - b) ** 2) / (2*sigma ** 2)) + k
    return array


def checkers_grid(shape, sq_size, odd_even=1):
    if odd_even not in (0, 1):
        raise ValueError('odd_even must be 0 or 1')
    grid = np.empty(shape)
    grid[:,:] = np.nan
    ind = np.indices(grid.shape)
    grid[(ind[0] // sq_size + ind[1] // sq_size) % 2 == odd_even] = 1
    return grid
    

def find_non_nan_coord(grid):
    return np.where(np.nonzero(grid))


def find_max_temp_index(temp):
    x, y = np.unravel_index(np.nanargmax(temp), temp.shape)
    return x, y


def gaussian2D(xy, h_1, h_2, amp, k, sigma):
    x_1, x_2 = xy
    return (amp * np.exp(-((x_1 - h_1) ** 2 + (x_2 - h_2) ** 2) / (2 * (sigma ** 2)))+k).ravel()


def fit_2Dgauss(grid):
    a, b = find_max_temp_index(grid)
    x, y = np.indices(grid.shape)
    params, cov = curve_fit(gaussian2D
                            ,(x.ravel(), y.ravel())
                            ,grid.ravel()
                            ,p0=[a, b, 200, 24, 1]
                            ,nan_policy='omit')
    return params, cov

g_array = create_gaussian_array((32, 24), (15.56, 11.23), 203.5, 10.4, 3.5)
g_even, g_odd = checkers_grid(g_array.shape, 4, 0)*g_array, checkers_grid(g_array.shape, 4, 1)*g_array
params_even, cov_even = fit_2Dgauss(g_even)
params_odd, cov_odd = fit_2Dgauss(g_odd)
print(params_even)
print(params_odd)

[ 15.56  11.23 203.5   10.4    3.5 ]
[ 15.56  11.23 203.5   10.4    3.5 ]
