In [35]:
import numpy as np


def checkers_grid(shape, sq_size, odd_even=1):
    if odd_even not in (0, 1):
        raise ValueError('odd_even must be 0 or 1')
    grid = np.zeros(shape, dtype=int)
    ind = np.indices(grid.shape)
    grid[(ind[0] // sq_size + ind[1] // sq_size) % 2 == odd_even] = 1
    return grid

print(checkers_grid((24, 32), 4, 0))

[[1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0]
 [1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0]
 [1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0]
 [1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]
 [0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]
 [0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]
 [0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0]
 [1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0]
 [1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0]
 [1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]
 [0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]
 [0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 

In [37]:
def create_circular_array(size, max_value):
    center = (size - 1) / 2
    array = np.zeros((size, size))
    for i in range(size):
        for j in range(size):
            distance = np.sqrt((i - center) ** 2 + (j - center) ** 2)
            array[i, j] = max(0, max_value - distance)
    return array

circular_array = create_circular_array(9, 9)
print(circular_array)

[[3.34314575 4.         4.52786405 4.87689437 5.         4.87689437
  4.52786405 4.         3.34314575]
 [4.         4.75735931 5.39444872 5.83772234 6.         5.83772234
  5.39444872 4.75735931 4.        ]
 [4.52786405 5.39444872 6.17157288 6.76393202 7.         6.76393202
  6.17157288 5.39444872 4.52786405]
 [4.87689437 5.83772234 6.76393202 7.58578644 8.         7.58578644
  6.76393202 5.83772234 4.87689437]
 [5.         6.         7.         8.         9.         8.
  7.         6.         5.        ]
 [4.87689437 5.83772234 6.76393202 7.58578644 8.         7.58578644
  6.76393202 5.83772234 4.87689437]
 [4.52786405 5.39444872 6.17157288 6.76393202 7.         6.76393202
  6.17157288 5.39444872 4.52786405]
 [4.         4.75735931 5.39444872 5.83772234 6.         5.83772234
  5.39444872 4.75735931 4.        ]
 [3.34314575 4.         4.52786405 4.87689437 5.         4.87689437
  4.52786405 4.         3.34314575]]


In [ ]:
# Create a 2D array with a Gaussian function
def create_gaussian_array(size, sigma):
    center = (size - 0.5) / 2
    array = np.zeros((size, size))
    for i in range(size):
        for j in range(size):
            distance = (i - center) ** 2 + (j - center) ** 2
            array[i, j] = np.exp(-distance / (2 * sigma ** 2))
    return array